services:
  jasminegraph:
    image: jasminegraph:latest
    ports:
      - '7777:7777'
      - '7778:7778'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
      - './env/databases/metadb:/home/ubuntu/software/jasminegraph/metadb'
      - './env/databases/performancedb:/home/ubuntu/software/jasminegraph/performancedb'
      - './env/data:/var/tmp/data'
      - '/tmp/jasminegraph:/tmp/jasminegraph'
      - '/var/tmp/jasminegraph:/var/tmp/jasminegraph'
      - './conf:/home/ubuntu/software/jasminegraph/conf'
    networks:
      jasminenet:
        ipv4_address: 172.28.5.5
    command: --MODE 1 --MASTERIP 172.28.5.1 --WORKERS 2 --WORKERIP 172.28.5.1 --ENABLE_NMON false
    depends_on:
      - prometheus
      - kafka
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - './conf/prometheus.yaml:/etc/prometheus/prometheus.yml'
    networks:
      jasminenet:
        ipv4_address: 172.28.5.2
    depends_on:
      - pushgateway
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
    networks:
      jasminenet:
        ipv4_address: 172.28.5.3
  kafka:
    image: apache/kafka:3.9.0
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://172.28.5.4:9092,CONTROLLER://172.28.5.4:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.28.5.4:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@172.28.5.4:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      CLUSTER_ID: ciWo7IWazngRchmPES6q5A==
    networks:
      jasminenet:
        ipv4_address: 172.28.5.4
networks:
  jasminenet:
    external: false
    name: jasminenet
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.5.0/24
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.1
