apiVersion: v1
kind: PersistentVolume
metadata:
  name: jasminegraph-metadb
  labels:
    application: jasminegraph
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: jasminegraph-metadb-claim
  hostPath:
    path: "${metadb_path}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasminegraph-metadb-claim
  labels:
    application: jasminegraph
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jasminegraph-performancedb
  labels:
    application: jasminegraph
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: jasminegraph-performancedb-claim
  hostPath:
    path: "${performancedb_path}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasminegraph-performancedb-claim
  labels:
    application: jasminegraph
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jasminegraph-data
  labels:
    application: jasminegraph
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "${data_path}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasminegraph-data-claim
  labels:
      application: jasminegraph
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-config
  labels:
    application: jasminegraph
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${config_directory_path}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-config-claim
  labels:
      application: jasminegraph
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jasminegraph-logs
  labels:
    application: jasminegraph
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "${log_path}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasminegraph-logs-claim
  labels:
      application: jasminegraph
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jasminegraph-aggregate
  labels:
    application: jasminegraph
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "${aggregate_path}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasminegraph-aggregate-claim
  labels:
    application: jasminegraph
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
